name: COMP3104 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Exercise 03
        run: echo "COMP3104 Exercise 03 GitHub Actions workflow completed successfully"